### ISSUE TITLE
CPU temp increase while enabled

### ISSUE THREAD

**Issue by AngryMustache** [Jukkales/NecroLens#1]
CPU Temp Increases
With this plugin enabled, inside and outside of deep dungeon causes a huge temperature spike on my system. I have a 7700x and enabled cpu temp is 72-80c, once I disable the plugin the cpu temp drops to 54c.

Not a developer so not entirely sure but it's entirely caused by this plugin. I do like the concept of this plugin though. Currently cannot use it in it's current state.

**Where?**
Everywhere inside and outside deep dungeons, as long as the plugin is enabled.

**Comment by Jukkales** [comment]
You got me with a nice beginner-style oopsie :D
Pushed a fix - it should run with much less cpu load now
