### ISSUE TITLE
Missing Patrol Mark

### ISSUE THREAD

**Issue by pincoide** [Jukkales/NecroLens#11]
**Describe the bug**
Just found that the heavenly onmitsu patrol mob is not marked as patrol (arrow mark). Not sure if it's not marked as patrol by design tho since it patrols only from floor 31 to 35 then they settle down :D

**Where?**
Instance:  HoH 
Floor: 31-35
Mob or Objectname: Heavenly Onmitsu

**Comment by Jukkales** [comment]
Quick question aside. There are two Heavenly Onmitsu on these floors - one i have marked as patrol. 
It SHOULD be the green one, but maybe im mistaken. Did you saw the arrow on the red one 34+?

**Comment by pincoide** [comment]
As far as I could see none of them has the arrow

**Comment by pincoide** [comment]
I've done a new run and the 2 onmitsu seems identical...
this is the patrol:
![image](https://github.com/Jukkales/NecroLens/assets/4291310/212d3162-108a-4d4b-93c3-d934ee081afc)

and this one at floor 34+ (NON patrol):
![image](https://github.com/Jukkales/NecroLens/assets/4291310/7480b46b-e346-45c2-bee1-96b6c37a3f4e)

they even have the same abilities :/

**Comment by Jukkales** [comment]
Pushed some updates and should work now

**Comment by pincoide** [comment]
I thought it was fixed because last run I saw the patrol correctly but I saw no onmitsu on 34+. I'm on a new run now and the onmitsu at 34+ are also marked as patrol when they are not (so the problem now is the opposite) 😆

**Comment by pincoide** [comment]
Will do, I'm trying to get to 100 solo in the spare time so I'll surely go by that floor set again and again and again XD

**Comment by pincoide** [comment]
ok, here we have the CORRECT patrol:
![image](https://github.com/Jukkales/NecroLens/assets/4291310/23b2ba26-d5da-47ba-a5b3-cd5c7e8bbac6)

and here we have the guy that should NOT be marked as patrol:
![image](https://github.com/Jukkales/NecroLens/assets/4291310/7af71d71-8de1-4865-9e44-9e910354af20)

to recap: 
D:8922 = patrol
D:8916 = normal

**Comment by Jukkales** [comment]
here we are now
fixed in 1.0.5.6
