### ISSUE TITLE
PoTD 181+ Sprite

### ISSUE THREAD

**Issue by spectrophile** [Jukkales/NecroLens#12]
The sprites on PoTD floors 181+ are marked as Sound, but they should be marked as Sight.

**Where?**
Instance: PoTD
Floor: 181+
Mob or Objectname: Deep Palace Sprite

**Comment by Jukkales** [comment]
Pushed some updates and should work now - can't really test it since i dont have a char or group up that high :/

**Comment by spectrophile** [comment]
Thanks so much! Will check it out when I get back up there.

**Comment by SClemensWW** [comment]
Can confirm this has been fixed!
