### ISSUE TITLE
No overlay for floors 181-190 in potd

### ISSUE THREAD

**Issue by ToshiHitoshi** [Jukkales/NecroLens#2]
**Describe the bug**
Overlay doesn't show up for floor 181-190. Not sure about 191+, I died earlier :)

**Where?**
Instance: PotD
Floor: 181-190

**Comment by Jukkales** [comment]
welp ... potd 111+ is the only range i wasnt able to test myself enough. just hoped that it all was like usual.

But one question to be sure: Is it only the helper window not showing up or even not the aggro draws on mobs?

**Comment by ToshiHitoshi** [comment]
both overlay and aggro draws weren't showing up unfortunately. 111-180 were ok though!

**Comment by Jukkales** [comment]
fixed in 1.0.2.4 - i just straight up forgot 181+ ... ._.

**Comment by ToshiHitoshi** [comment]
I'm still working my way back up to 181+ to test, but I noticed 51-60 potd is also broken now with the latest version. Helper window shows up, but no overlay for chests or aggro draw on mobs.
