### ISSUE TITLE
6.4 update is unstable 

### ISSUE THREAD

**Issue by laziest-cat** [Jukkales/NecroLens#5]
It's super inconsistent. 
One floor, everything could be alright, while in the next it doesn't mark anything or show any aggro cones/circles. Or it straight up shows things wrong (i.e. showing the Passage as a gold chest). Or some things show up while others don't on the same floor.
Just thought I'd let you know.

**Comment by asdebeaubien** [comment]
I'm also having this same issue. (Note for Jukkales: Love your work!!!)

**Comment by Jukkales** [comment]
closing this one to continue this issue in #6
