### ISSUE TITLE
6.4 Crash

### ISSUE THREAD

**Issue by pincoide** [Jukkales/NecroLens#6]
When ESP overlay is enabled, the monsters sight area works at first, but after attacking a few monsters it stops working and eventually the client crashes.
There is no crash log after that so I can't be 100% sure if it's conflicting with palace pal, but since it worked fine before the patch and with the ESP overlay turned off the crash stops we can be sure there is something wrong with necrolens.

Btw, after the sight area disappears, I tried to turn off and on the plugin to see if the issue was termporary but the moment I click the button to turn off the plugin the client crashes.

**Comment by laziest-cat** [comment]
Having the same issue.

**Comment by Jukkales** [comment]
Guess its the same reason as #5 - need to check it closer. Just tested if it shows up haha.
I take a look in it, but it might need some time since im a bit busy over the weekend.

**Comment by Jukkales** [comment]
Pushed a "workaround" to prevent the crashes and instability. The root cause seems like to come from dalamud itself. Asked there for assistence. It should work like normal again but it MAY not show up single objects like traps or chests. If i find how to fix the root cause i will implement it :3

**Comment by pincoide** [comment]
I tried for a couple of hours and the sight area seems to work well and no crashes, thanks 😄
