### ISSUE TITLE
main window not opening since latest patch

### ISSUE THREAD

**Issue by Noshei** [Jukkales/NecroLens#8]
since the patch today the main window wont open.  It didn't open automatically when entering HoH and the /necrolens command also didn't work to open it.  The config window does open and the options seems to all work.

**Comment by D34Final** [comment]
Same for me

**Comment by Jukkales** [comment]
yes this is correct, there was a client update and i need to update the plugin. im at hospital rn and cant update it till weekend.

**Comment by Jukkales** [comment]
Its updated now. Sorry for the very long delay :(
